version: "3.8"

services:

  portfolio:
    build: ./docker-project
    container_name: devops-web
    expose:
      - "5000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - portfolio
    restart: unless-stopped
